version: '3'
services:
  service-registry:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      service-registry:
        condition: service_healthy

  postgres-accounts:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accounts-service
    container_name: postgres-accounts

  postgres-transactions:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transactions-service
    container_name: postgres-transactions

  postgres-notifications:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notifications-service
    container_name: postgres-notifications

  postgres-auth:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth-service
    container_name: postgres-auth


  account_management-service:
    build:
      context: ./account_management-service
    container_name: account_management-service
    ports:
      - "8085:8085"
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-accounts:5432/accounts-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy

  transactions-service:
    build:
      context: ./transactions-service
    container_name: transactions-service
    ports:
      - "8081:8081"
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-transactions:5432/transactions-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    expose:
      - '8088'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-notifications:5432/notifications-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - User-Access-Token=Bearer EAAFm4nayQpgBO6XTxYTdVQR9PfZCU81lsffQhF2wHj9Olgo2kh64iVHfw9KzqAC9gGKddHRzx5DT0kcpSejwi7iyX0Lb9jNY0AZBZBJICZApitmdqIcU0ZBJzsS8uqbx5cbUeiR7Dq29LiqkcSBpVZCWaRDuSScqrpTmGNuDDixTRKOPaAo7pUtCR8UvYKFk2di7fPbUCxCg4eIQmZAnddhR1aqq4rmpWgJiUsZD
      - Url=https://graph.facebook.com/v19.0/294334807093557/messages
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/auth-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy








